service: peanut-butter-box-cloud-front-edge
  
configValidationMode: error
  
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  lambdaHashingVersion: 20201221
    
functions:
  ui-gateway-edge:
    handler: src/index.handler
    events:
      - preExistingCloudFront:
          distributionId: E2H9UFCQVN4CUB
          eventType: origin-request
          pathPattern: '*'
          includeBody: true
plugins:
  - serverless-lambda-edge-pre-existing-cloudfront
  - serverless-plugin-typescript

resources:
  Resources:
    IamRoleLambdaExecution:
      Type: "AWS::IAM::Role"
      Properties:
        AssumeRolePolicyDocument:
          Statement: 
            - Effect: Allow
              Principal: 
                Service:
                  - lambda.amazonaws.com
                  - edgelambda.amazonaws.com